### ISSUE TITLE
not work?

### ISSUE THREAD

**Issue by liamxg** [agmcfarland/r_phylogenetics_worshop#1]
tree_raxml_outgrouproot_visual6$node.label[as.numeric(tree_raxml_outgrouproot_visual6$node.label)<70] <- 'a'

tree_raxml_outgrouproot_visual6$node.label[as.numeric(tree_raxml_outgrouproot_visual6$node.label)>=70 &as.numeric(tree_raxml_outgrouproot_visual6$node.label)<90] <- 'b'

tree_raxml_outgrouproot_visual6$node.label[as.numeric(tree_raxml_outgrouproot_visual6$node.label)>=90] <- 'c'

**Comment by liamxg** [comment]
@agmcfarland

**Comment by agmcfarland** [comment]
Hi @LiXingguangBrandonStark, could you please post what the error message is? Thank you!

**Comment by liamxg** [comment]
<img width="409" alt="image" src="https://user-images.githubusercontent.com/46078579/191447292-2bf3c77c-4b45-491b-9cd3-db599d5997e4.png">

**Comment by liamxg** [comment]
@agmcfarland no error, but no a, b, c are labeled in the node?

**Comment by agmcfarland** [comment]
Thanks, I will look into it!

**Comment by agmcfarland** [comment]
Hi @LiXingguangBrandonStark,

Replace tree_raxml_outgrouproot_visual6  with tree_raxml_outgrouproot and it will work.

**Comment by liamxg** [comment]
thanks, I will try that.

**Comment by liamxg** [comment]
@agmcfarland

**Comment by liamxg** [comment]
tree_raxml <- ape::read.tree('RAxML_bipartitions.raw_enoyl_seqs')

tree_raxml_outgrouproot <- ape::root(tree_raxml ,outgroup='tr|E6KYQ2|E6KYQ2_9PAST')

tree_raxml_outgrouproot_visual6 <- ggtree(tree_raxml_outgrouproot)+
  geom_tiplab(size=2,offset=0.1)+
  geom_tippoint()+
  geom_nodelab(aes(label=label),nudge_x=-.1,nudge_y=.4,size=2)+
  geom_treescale(x=7, color=NA)

tree_raxml_outgrouproot_visual6 <- collapse(tree_raxml_outgrouproot_visual6, node=24,'max')

tree_raxml_outgrouproot_visual6$node.label[as.numeric(tree_raxml_outgrouproot_visual6$node.label)<70] <- 'a'

tree_raxml_outgrouproot_visual6$node.label[as.numeric(tree_raxml_outgrouproot_visual6$node.label)>=70 &as.numeric(tree_raxml_outgrouproot_visual6$node.label)<90] <- 'b'

tree_raxml_outgrouproot_visual6$node.label[as.numeric(tree_raxml_outgrouproot_visual6$node.label)>=90] <- 'c'

tree_raxml_outgrouproot_visual6 <- tree_raxml_outgrouproot_visual6 +
  geom_highlight(node=35, 'lightblue')+
  geom_cladelabel(node=35, label='fabG', align=TRUE,offset = 1.2, angle=90, vjust=2, hjust=0.5)+
  geom_cladelabel(node=24, label='fabV', align=TRUE,offset = -.2, angle=90, vjust=2, hjust=0.5)+
  geom_cladelabel(node=2, label='novel\nfabG', align=TRUE,offset = 1.1, angle=90, vjust=2, hjust=0.5, color='blue')

tree_raxml_outgrouproot_visual6

**Comment by liamxg** [comment]
@agmcfarland not work

**Comment by liamxg** [comment]
anything that i missed?
